apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-app-prd
  namespace: argocd
  labels:
    fintoc_com_repo: poc-app
    fintoc_com_env: production
spec:
  project: default
  source:
    repoURL: https://github.com/mpenalozag/fake-underworld-k8s.git
    targetRevision: HEAD
    path: prd
  destination:
    server: https://kubernetes.default.svc
    namespace: poc-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
