apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poc-app
resources:
  - rollout.yaml
  - migration-job.yaml
  - service.yaml
# image-updater reescribe newTag cada vez que hay una imagen nueva con tag matching
# el regex de la Application (^[a-f0-9]{40}$ para stg).
images:
  - name: ghcr.io/mpenalozag/poc-app
    newTag: 1778248607-f3eba9824fcd054d7f8ee158792a053295e211b8
commonLabels:
  fintoc_com_repo: poc-app
  fintoc_com_env: staging
  fintoc_com_target: poc-app-stg
