apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: poc-app-stg-5
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.hive: ""
    notifications.argoproj.io/subscribe.on-rollout-failed.hive: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-app-stg-5
  template:
    metadata:
      labels:
        app: poc-app-stg-5
        fintoc_com_repo: poc-app
        fintoc_com_env: staging
        fintoc_com_target: poc-app-stg
    spec:
      containers:
        - name: app
          image: ghcr.io/mpenalozag/poc-app:placeholder
          resources: {}
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: postgres://poc:poc@postgres.poc-app.svc.cluster.local:5432/poc_stg
            - name: RACK_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 60
